const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('photo-archive.html', 'utf8');
const publicHtml = fs.readFileSync('photo-share.html', 'utf8');
const client = fs.readFileSync('assets/js/photo-archive.js', 'utf8');
const publicClient = fs.readFileSync('assets/js/photo-share.js', 'utf8');
const server = fs.readFileSync('server/photo-archive/photo_archive.py', 'utf8');
const docker = fs.readFileSync('server/photo-archive/Dockerfile', 'utf8');
const top = fs.readFileSync('toppage.html', 'utf8');
const monitor = fs.readFileSync('system_monitor.html', 'utf8');

assert.match(top, /撮影記録アーカイブ/);
assert.match(html, /auth_guard\.js/);
assert.match(html, /firebase-data-auth\.js/);
assert.match(html, /個人一覧/);
assert.match(html, /共有一覧/);
assert.match(html, /マップ/);
assert.match(html, /カレンダー/);
assert.match(html, /ゴミ箱/);
assert.match(html, /PRA-01/);
assert.match(html, /api-status/);
assert.match(html, /PHOTO RECORD MANAGEMENT SYSTEM/);
assert.match(html, /id="filter-toggle"/);
assert.match(html, /id="filter-backdrop"/);
assert.match(html, /id="mobile-menu-button"/);
assert.match(html, /id="mobile-action-menu"/);
assert.match(html, /id="mobile-friend-button"/);
assert.match(html, /id="friend-notification"/);
assert.match(html, /id="menu-notification"/);
assert.match(html, /id="mobile-friend-notification"/);
assert.match(html, /id="mobile-logout-button"/);
assert.match(html, /id="content-loading"/);
assert.match(html, /id="upload-submit"/);
assert.match(html, /id="upload-member-picker"/);
assert.match(html, /id="help-dialog"/);
assert.match(html, /使い方・機能概要/);
assert.match(html, /JPEG（JPG）・PNG・WebP・TIFF/);
assert.match(html, /name="shutterSpeed"/);
assert.match(html, /name="iso"/);
assert.match(html, /viewport-fit=cover/);
assert.doesNotMatch(html, /unpkg\.com\/leaflet/i);
assert.match(html, /file[^>]+multiple/);
assert.match(client, /XMLHttpRequest/);
assert.match(client, /xhr\.upload\.onprogress/);
assert.match(client, /\/v1\/export\/originals\.zip/);
assert.match(client, /allowedGroupIds/);
assert.match(client, /写真API 正常/);
assert.match(client, /function loadLeaflet/);
assert.match(client, /preferCanvas: true/);
assert.match(client, /circleMarker/);
assert.match(client, /setPrimarySurface\("map"\)/);
assert.match(client, /filters-open/);
assert.match(client, /setMobileMenuOpen/);
assert.match(client, /friendlyError/);
assert.match(client, /setContentLoading/);
assert.match(client, /setButtonBusy/);
assert.match(client, /retryTransient && \["GET", "HEAD"\]\.includes\(method\)/);
assert.match(client, /\[502, 503, 504\]\.includes\(response\.status\)/);
assert.match(client, /detailRenderId: 0/);
assert.match(client, /renderId !== state\.detailRenderId \|\| !dialog\.open/);
assert.match(client, /if\(dialog\.id==="detail-dialog"\)state\.detailRenderId\+\+/);
assert.match(client, /edit-section basic/);
assert.match(client, /edit-section train/);
assert.match(client, /edit-section equipment/);
assert.match(client, /edit-section sharing/);
assert.match(client, /共有リンクを安全に作成しています/);
assert.match(client, /xhr\.timeout=10\*60\*1000/);
assert.match(client, /fileMetadata/);
assert.match(client, /data-file-field/);
assert.match(client, /管理モード（登録不可）/);
assert.match(client, /function setPrimarySurface/);
assert.match(client, /function updateEmptyState/);
assert.match(client, /function mergeSharePeople/);
assert.match(client, /function prepareUploadSharing/);
assert.match(client, /const PHOTO_CATEGORIES/);
for (const label of ["定期旅客列車", "貨物列車", "回送列車", "試運転列車", "多客・旅客臨・団臨等", "配給列車", "工事列車", "新幹線", "私鉄", "陸送", "車", "航空"]) assert.match(client, new RegExp(label));
assert.match(client, /function editAlbumSharing/);
assert.match(client, /data-share-album-members/);
assert.match(client, /function exifSummary/);
assert.match(client, /function updateFriendNotification/);
assert.match(client, /function refreshFriendNotifications/);
assert.match(client, /function currentAccountSearch/);
assert.match(client, /現在ログイン中のアカウントです/);
assert.match(client, /photo_member_directory/);
assert.match(client, /該当する承認済み利用者はいません/);
assert.match(client, /あなたへの申請/);
assert.match(client, /あなたが送った申請/);
assert.match(client, /name="albumIds"/);
assert.match(client, /raw\.albumIds=/);
assert.match(client, /data-share-members/);
assert.match(client, /editDetail\(photo,true\)/);
assert.match(client, /calendar-month/);
assert.match(client, /\/v1\/me/);
assert.match(client, /おすすめ|候補/);
assert.match(publicHtml, /share-password/);
assert.match(publicHtml, /share-unlock-status/);
assert.match(publicClient, /X-Share-Password/);
assert.match(publicClient, /retry-share/);
assert.match(publicClient, /AbortController/);
assert.match(server, /ImageOps\.exif_transpose/);
assert.match(server, /GPSLatitude/);
assert.match(server, /hashlib\.scrypt/);
assert.match(server, /deleted_at/);
assert.match(server, /TRASH_DAYS/);
assert.match(server, /verify_user/);
assert.match(server, /allowed_group_ids_json/);
assert.match(server, /admin@tayunet-traininfo\.com/);
assert.match(server, /systemadmin@tayunet-traininfo\.com/);
assert.match(server, /def require_contributor/);
assert.match(server, /active_directory_profile/);
assert.match(server, /fileMetadata/);
assert.match(server, /@app\.patch\("\/v1\/albums\/\{album_id\}"\)/);
assert.match(server, /@app\.delete\("\/v1\/friends/);
assert.doesNotMatch(server, /firebase.*password/i);
assert.match(docker, /python3 -m unittest/);
assert.match(monitor, /photo-api\.tayunet-traininfo\.com\/health/);

const css = fs.readFileSync('assets/css/photo-archive.css', 'utf8');
assert.match(css, /iPad \/ tablet modal viewport containment/);
assert.match(css, /\.archive-dialog\[open\][^{]*\{[^}]*100dvh/);
assert.match(css, /min-width:601px\) and \(max-width:900px/);
assert.match(css, /\.detail-dialog \.detail-data\{[^}]*overflow-y:auto/);
assert.match(css, /\.upload-dialog \.dialog-actions\{[^}]*position:sticky/);
assert.match(css, /\[hidden\]\{display:none!important\}/);
assert.match(css, /\.content\.dedicated-scope \.view-buttons/);
assert.match(css, /\.calendar-grid/);
assert.match(css, /\.member-picker/);
assert.match(css, /\.edit-section label/);
assert.match(css, /\.notification-badge/);
assert.match(css, /\.member-share-shortcut/);
assert.match(css, /\.self-search-result/);
assert.match(css, /\.current-account-note/);
assert.match(css, /\.archive-header>\.site-brand-link\{grid-column:1/);
assert.match(css, /grid-template-columns:auto minmax\(0,1fr\) auto/);
assert.match(css, /\.help-dialog\[open\]/);
assert.match(css, /\.upload-equipment/);
assert.match(css, /\.album-sharing-form/);

console.log('photo archive audit: ok');
