const $ = id => document.getElementById(id);
const ODPT_ACCESS_TOKEN = '26d1y7j8fkzdabx6iuxby79nqu8tdz8h6mmu05apwseyvg8h9uvymkl5y9ikpo9o';
const ODPT_GTFS_URL = `https://api-challenge.odpt.org/api/v4/files/JR-Freight/data/JR-Freight-Train-GTFS-2500.zip?acl:consumerKey=${ODPT_ACCESS_TOKEN}`;
const state = {
  db:null, infos:new Map(), stations:[], stationTrips:new Map(), favorites:new Set(), compare:new Set(), shards:new Map(), status:null, logs:[],
  view:'dashboard', selected:null, selectedStation:null, visibleTrips:60, boardMode:'all', mapMode:'network',
  map:null, mapBase:0, mapLayers:[], networkLayer:null, routeLayer:null, routeStops:null, trainMarker:null, detailMap:null,
  settings:{theme:'light',density:'comfortable',delay:true,estimate:true,autoRefresh:false}, autoTimer:null
};

function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function mins(value){if(!value)return null;const [h,m]=value.split(':').map(Number);return h*60+m;}
function shortTime(value){if(!value)return '—';const [h,m]=value.split(':');return `${h}:${m}`;}
function displayTime(value){if(!value)return '—';const total=mins(value),day=Math.floor(total/1440),clock=`${String(Math.floor((total%1440)/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`;return day?`+${day}日 ${clock}`:clock;}
function parseDate(s){return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;}
function nowMinute(){const d=new Date();return d.getHours()*60+d.getMinutes();}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function durationText(total){if(total==null||total<0)return '—';const days=Math.floor(total/1440),hours=Math.floor((total%1440)/60),minutes=total%60;return `${days?`${days}日 `:''}${hours}時間${String(minutes).padStart(2,'0')}分`;}
function trainNumber(id){
  return id.split('_').slice(2).map(part=>{if(part==='d')return '配送';const road=part.endsWith('b');let n=part.replace(/b$/,'').replace(/^0+/,'');if(n.length>4)n=n.slice(0,-2);return `${n||'0'}${road?'便':'レ'}`;}).join(' → ');
}
function logEvent(level,message,detail=''){
  const entry={time:new Date(),level,message,detail};state.logs.push(entry);if(state.logs.length>300)state.logs.shift();
  if(level==='error')console.error(`[Cargo Scope] ${message}`,detail);else if(level==='warn')console.warn(`[Cargo Scope] ${message}`,detail);else console.info(`[Cargo Scope] ${message}`,detail);
  renderConsole();
}
function renderConsole(){
  const root=$('consoleLogs');if(!root)return;const errors=state.logs.filter(x=>x.level==='error').length;$('consoleErrorBadge').textContent=errors;$('consoleErrorBadge').classList.toggle('hidden',!errors);$('consoleLogCount').textContent=`${state.logs.length}件`;$('consoleOverall').innerHTML=errors?`<i class="status-ok" style="background:var(--red)"></i> ${errors}件のエラー`:'<i class="status-ok"></i> システム正常';
  root.innerHTML=state.logs.slice().reverse().map(x=>`<div class="console-line"><span class="console-time">${x.time.toLocaleTimeString('ja-JP',{hour12:false})}</span><span class="console-level ${x.level}">${x.level.toUpperCase()}</span><span class="console-message">${esc(x.message)}${x.detail?`<small class="console-detail">${esc(x.detail)}</small>`:''}</span></div>`).join('')||'<div class="empty-row">ログはまだありません</div>';
}
function statusNumbers(service=''){const before=service.split('列車')[0].replace(/^\d+日発/,'');return(before.match(/\d+/g)||[]).map(n=>String(Number(n)));}
function infoNumbers(info){return trainNumber(info.trip[0]).match(/\d+/g)||[];}
function delayRecord(info){
  if(!state.settings.delay||!state.status?.ok)return null;const numbers=new Set(infoNumbers(info));const matches=state.status.trains.filter(t=>statusNumbers(t.service).some(n=>numbers.has(n)));if(!matches.length)return null;
  return matches.sort((a,b)=>delayMinutesFromStatus(b.status)-delayMinutesFromStatus(a.status))[0];
}
function delayMinutesFromStatus(text=''){const hour=Number(text.match(/([0-9]+)時間/)?.[1]||0),minute=Number(text.match(/([0-9]+)分/)?.[1]||0);return hour*60+minute;}
function delayMinutes(info){const record=delayRecord(info);return record?delayMinutesFromStatus(record.status):0;}
function adjustedTime(time,delay){if(!time||!delay)return time;const total=mins(time)+delay;return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}:00`;}
function timelineFor(trip){
  const all=(state.db.stopTimes[trip[0]]||[]).slice().sort((a,b)=>a[3]-b[3]).map(x=>({id:x[0],arr:x[1],dep:x[2],stop:state.db.stops[x[0]]})).filter(x=>x.stop);
  const grouped=[];
  for(const x of all){const code=x.stop[0];let g=grouped.find(y=>y.code===code);if(!g){g={code,name:x.stop[1],lat:x.stop[2],lon:x.stop[3],arr:'',dep:'',cargo:false,train:false};grouped.push(g);}if(x.id.startsWith('C')){g.cargo=true;if(x.arr)g.arr=x.arr;if(x.dep)g.dep=x.dep;}if(x.id.startsWith('T')){g.train=true;if(x.arr)g.arr=x.arr;if(x.dep)g.dep=x.dep;}}
  return grouped;
}
function tripInfo(trip){
  if(state.infos.has(trip[0]))return state.infos.get(trip[0]);
  const timeline=timelineFor(trip),times=timeline.flatMap(s=>[s.dep,s.arr]).filter(Boolean).map(mins),first=times.length?Math.min(...times):null,last=times.length?Math.max(...times):null;
  const legs=trip[0].split('_').slice(2),roadLegs=legs.filter(x=>x==='d'||x.endsWith('b')).length,railLegs=legs.length-roadLegs;
  const info={trip,timeline,first,last,from:timeline[0]?.name||'—',to:timeline.at(-1)?.name||trip[2]||'—',duration:first==null||last==null?null:last-first,offrail:timeline.some(s=>/オフレール|営業所/.test(s.name))||roadLegs>0,roadLegs,railLegs,route:state.db.routes[trip[1]]?.name||'方面未設定'};
  state.infos.set(trip[0],info);return info;
}
function activeRelative(info){
  if(info.first==null||info.last==null)return null;const current=nowMinute(),delay=delayMinutes(info),maxDays=Math.ceil((info.last+delay)/1440)+1;
  for(let day=0;day<=maxDays;day++){const relative=current+day*1440;if(info.first+delay<=relative&&relative<=info.last+delay)return relative-delay;}return null;
}
function isActive(info){return activeRelative(info)!==null;}
function nextDelta(time){if(!time)return Infinity;return ((mins(time)%1440)-nowMinute()+1440)%1440;}
function departureTime(info){return info.timeline.find(s=>s.dep)?.dep||info.timeline.find(s=>s.arr)?.arr||'';}
function arrivalTime(info){return [...info.timeline].reverse().find(s=>s.arr)?.arr||[...info.timeline].reverse().find(s=>s.dep)?.dep||'';}
function tripProgress(info){const rel=activeRelative(info);return rel==null||!info.duration?0:Math.max(0,Math.min(100,Math.round((rel-info.first)/info.duration*100)));}

function loadPrefs(){
  try{state.settings={...state.settings,...JSON.parse(localStorage.getItem('cargoScopeSettings')||'{}')};state.favorites=new Set(JSON.parse(localStorage.getItem('cargoScopeFavorites')||'[]'));}catch{}
  applyPrefs();
}
function savePrefs(){localStorage.setItem('cargoScopeSettings',JSON.stringify(state.settings));localStorage.setItem('cargoScopeFavorites',JSON.stringify([...state.favorites]));applyPrefs();$('settingsSaved').textContent=`保存しました ${new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}`;}
function actualTheme(){return state.settings.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):state.settings.theme;}
function applyPrefs(){const theme=actualTheme();document.documentElement.dataset.theme=theme;document.documentElement.dataset.density=state.settings.density;document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#0f151d':'#f7f9fc';$('themeButton').textContent=theme==='dark'?'☀':'☾';$('densitySelect').value=state.settings.density;$('delayToggle').checked=state.settings.delay;$('estimateToggle').checked=state.settings.estimate;$('autoRefreshToggle').checked=state.settings.autoRefresh;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===state.settings.theme));setupAutoRefresh();}
function setupAutoRefresh(){clearInterval(state.autoTimer);if(state.settings.autoRefresh)state.autoTimer=setInterval(refreshStatus,300000);}

async function fetchFreightStatus({quiet=false}={}){
  const panel=$('liveStatusPanel');panel.className='live-status loading';$('liveStatusTitle').textContent='現在の遅延情報を確認しています';$('liveStatusMeta').textContent='公式情報との接続を開始しました';
  if(!quiet)logEvent('info','JR貨物の輸送状況を取得しています','./data/freight-status.json');
  try{
    const response=await fetch(`./data/freight-status.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!data.ok)throw new Error(data.error||'遅延情報の形式が不正です');state.status=data;renderLiveStatus();
    logEvent('success','JR貨物の輸送状況を更新しました',`${data.asOf||'時刻不明'}｜${data.trains.length}列車・${data.routes.length}線区`);
    if(state.db){renderDashboard();if(state.view==='trains')renderTrips();if(state.selected)openTrip(state.selected.trip[0]);}
  }catch(error){state.status={ok:false,error:error.message};renderLiveStatus();logEvent('error','遅延情報を取得できませんでした',error.message);}
}
function renderLiveStatus(){
  const panel=$('liveStatusPanel'),data=state.status;if(!data?.ok){panel.className='live-status error';panel.querySelector('.live-status-icon').textContent='!';$('liveStatusTime').textContent='取得失敗';$('liveStatusTitle').textContent='遅延情報へ接続できません';$('liveStatusMeta').textContent='計画時刻表は引き続き利用できます。設定のコンソールで原因を確認してください。';$('delayTrainCount').textContent='—';$('delayRouteCount').textContent='—';return;}
  const delayed=data.trains.length>0;panel.className=`live-status ${delayed?'delay':''}`;panel.querySelector('.live-status-icon').textContent=delayed?'!':'✓';$('liveStatusTime').textContent=`${data.announcementDate||''} ${data.asOf||''}`.trim();$('liveStatusTitle').textContent=data.title|| (delayed?'貨物列車に遅れが発生しています':'現在、遅延情報はありません');$('liveStatusMeta').textContent=delayed?`${data.routes.length}線区・${data.trains.length}列車｜公式発表を列車番号でGTFSへ反映中`:'公式発表では遅延列車の掲載はありません';$('delayTrainCount').textContent=data.trains.length;$('delayRouteCount').textContent=data.routes.length;
}
function renderDelayDialog(){
  const data=state.status;if(!data?.ok){$('delayDialogContent').innerHTML=`<div class="empty-state"><span class="large-icon">!</span><h2>遅延情報を取得できません</h2><p>${esc(data?.error||'接続を確認してください')}</p></div>`;return;}
  $('delayDialogContent').innerHTML=`<div class="delay-overview"><div><span>公式発表</span><b>${esc(data.announcementDate)} ${esc(data.asOf)}</b></div><div><span>遅延列車</span><b>${data.trains.length}列車</b></div><div><span>影響線区</span><b>${data.routes.length}線区</b></div></div><h3>${esc(data.title)}</h3><ul class="incident-list">${data.incidents.map(i=>`<li><time>${esc(i.time)}</time><span>${esc(i.detail)}</span></li>`).join('')}</ul>${data.routes.map(route=>`<section class="delay-route"><h3>${esc(route.name)}</h3><div class="table-wrap"><table><thead><tr><th>列車</th><th>現在地</th><th>状況</th></tr></thead><tbody>${route.trains.map(t=>`<tr><td>${esc(t.service)}</td><td>${esc(t.location)}</td><td>${esc(t.status)}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}`;
}

function clock(){const now=new Date();$('clock').textContent=now.toLocaleTimeString('ja-JP',{hour12:false});}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),2600);}
function setView(name){
  state.view=name;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));
  if(name==='dashboard')renderDashboard();if(name==='trains')renderTrips();if(name==='stations')renderStations();if(name==='favorites')renderFavorites();if(name==='map'){initMap();stabilizeMap();renderMapPanel();}
  $('mainContent').scrollTop=0;
}

function buildIndexes(){
  const grouped=new Map();for(const stop of Object.values(state.db.stops)){const [code,name,lat,lon]=stop;if(!grouped.has(code))grouped.set(code,{code,name,lat,lon,type:/オフレール/.test(name)?'ORS':/営業所/.test(name)?'営業所':'貨物駅'});}
  state.stations=[...grouped.values()].sort((a,b)=>a.name.localeCompare(b.name,'ja'));
  for(const trip of state.db.trips){const info=tripInfo(trip);for(const stop of info.timeline){const list=state.stationTrips.get(stop.code)||[];list.push(info);state.stationTrips.set(stop.code,list);}}
}
function uniqueInfos(){return [...state.infos.values()];}

function renderDashboard(){
  if(!state.db)return;const infos=uniqueInfos(),active=infos.filter(isActive),upcoming=infos.filter(i=>{const d=nextDelta(departureTime(i));return d<=120;}).sort((a,b)=>nextDelta(departureTime(a))-nextDelta(departureTime(b)));
  $('activeKpi').textContent=active.length.toLocaleString();$('departKpi').textContent=upcoming.filter(i=>nextDelta(departureTime(i))<=60).length.toLocaleString();$('totalKpi').textContent=infos.length.toLocaleString();$('stationKpi').textContent=state.stations.length.toLocaleString();$('railRoadKpi').textContent=`鉄道 ${infos.filter(i=>!i.offrail).length.toLocaleString()} ／ ORS含む ${infos.filter(i=>i.offrail).length.toLocaleString()}`;
  $('dashboardSubtitle').textContent=`${$('dateInput').value.replaceAll('-','/')}のGTFS計画を表示中`;$('updatedAt').textContent=`${new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})} 更新`;
  const groups={};for(const i of active)groups[i.route]=(groups[i.route]||0)+1;const rows=Object.entries(groups).sort((a,b)=>b[1]-a[1]).slice(0,7),max=Math.max(1,...rows.map(x=>x[1]));
  $('regionBars').innerHTML=rows.length?rows.map(([name,count])=>`<div class="region-row"><span title="${esc(name)}">${esc(name)}</span><div class="bar-track"><div class="bar-fill" style="width:${count/max*100}%"></div></div><b>${count}</b></div>`).join(''):'<div class="empty-row">現在時刻に該当する計画はありません</div>';
  $('upcomingList').innerHTML=upcoming.slice(0,8).map(i=>`<div class="upcoming-item" data-trip="${esc(i.trip[0])}"><span class="upcoming-time">${displayTime(departureTime(i))}</span><div class="upcoming-main"><b>${esc(trainNumber(i.trip[0]))}</b><small>${esc(i.from)} → ${esc(i.to)}</small></div><span class="tag">${nextDelta(departureTime(i))}分後</span></div>`).join('')||'<div class="empty-row">120分以内の発車計画はありません</div>';
  $('activeTable').innerHTML=active.sort((a,b)=>tripProgress(b)-tripProgress(a)).slice(0,12).map(i=>{const delay=delayRecord(i);return `<tr data-trip="${esc(i.trip[0])}"><td><span class="train-name">${esc(trainNumber(i.trip[0]))}</span>${delay?`<br><span class="delay-badge">${esc(delay.status)}</span>`:''}</td><td>${esc(i.from)} → ${esc(i.to)}</td><td><span class="route-text">${esc(i.route)}</span></td><td>${displayTime(departureTime(i))} — ${displayTime(delay?adjustedTime(arrivalTime(i),delayMinutes(i)):arrivalTime(i))}</td><td><div class="progress"><div class="progress-track"><div class="progress-fill" style="width:${tripProgress(i)}%"></div></div><small>${tripProgress(i)}%</small></div></td><td>›</td></tr>`;}).join('')||'<tr><td colspan="6" class="empty-row">現在時刻に該当する計画はありません</td></tr>';
  bindTripOpen($('dashboardView'));
}

function filteredTrips(){
  const query=$('trainSearch').value.trim().toLowerCase(),route=$('routeSelect').value,status=$('statusSelect').value,sort=$('sortSelect').value;
  let rows=uniqueInfos().filter(i=>{if(route&&i.trip[1]!==route)return false;if(query&&!`${i.trip[0]} ${trainNumber(i.trip[0])} ${i.from} ${i.to} ${i.timeline.map(s=>s.name).join(' ')}`.toLowerCase().includes(query))return false;if(status==='delayed'&&!delayRecord(i))return false;if(status==='active'&&!isActive(i))return false;if(status==='upcoming'&&nextDelta(departureTime(i))>120)return false;if(status==='railonly'&&i.offrail)return false;if(status==='offrail'&&!i.offrail)return false;if(status==='roadleg'&&!i.roadLegs)return false;if(status==='direct'&&!(i.railLegs===1&&i.roadLegs===0))return false;if(status==='relay'&&i.railLegs<2)return false;return true;});
  rows.sort(sort==='duration'?(a,b)=>(a.duration||0)-(b.duration||0):sort==='train'?(a,b)=>trainNumber(a.trip[0]).localeCompare(trainNumber(b.trip[0]),'ja'):(a,b)=>(mins(departureTime(a))||9999)-(mins(departureTime(b))||9999));return rows;
}
function tripCard(info){const fav=state.favorites.has(info.trip[0]),comp=state.compare.has(info.trip[0]),delay=delayRecord(info),arrival=delay?adjustedTime(arrivalTime(info),delayMinutes(info)):arrivalTime(info);return `<article class="trip-card" data-trip="${esc(info.trip[0])}"><div class="trip-card-top"><h3>${esc(trainNumber(info.trip[0]))}</h3><button class="favorite-mini ${fav?'on':''}" data-favorite="${esc(info.trip[0])}" title="お気に入り">${fav?'★':'☆'}</button></div><div class="trip-route"><span>${esc(info.from)}</span><i class="route-arrow"></i><span>${esc(info.to)}</span></div><div class="trip-meta"><span>${displayTime(departureTime(info))} → ${displayTime(arrival)}</span><span>${info.timeline.length}地点</span></div>${delay?`<div class="trip-delay"><b>${esc(delay.status)}</b>｜${esc(delay.location)}｜到着見込へ反映</div>`:''}<div class="trip-actions"><span class="tag">${esc(info.route)}</span><button class="compare-mini ${comp?'on':''}" data-compare="${esc(info.trip[0])}">${comp?'比較中':'＋ 比較'}</button></div></article>`;}
function renderTrips(){if(!state.db)return;const rows=filteredTrips();$('resultCount').textContent=`${rows.length.toLocaleString()}件`;$('tripGrid').innerHTML=rows.slice(0,state.visibleTrips).map(tripCard).join('')||emptyCards('条件に合う輸送計画がありません');$('loadMoreButton').classList.toggle('hidden',rows.length<=state.visibleTrips);bindTripCards($('tripGrid'));}
function emptyCards(message){return `<div class="empty-state" style="grid-column:1/-1;padding:90px 20px"><span class="large-icon">⌕</span><h2>${esc(message)}</h2><p>検索条件を変更してください。</p></div>`;}
function bindTripCards(root){
  root.querySelectorAll('.trip-card').forEach(card=>card.onclick=e=>{if(e.target.closest('button'))return;openTrip(card.dataset.trip);});
  root.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.favorite);});root.querySelectorAll('[data-compare]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCompare(b.dataset.compare);});
}
function bindTripOpen(root){root.querySelectorAll('[data-trip]').forEach(el=>el.onclick=e=>{if(e.target.closest('button'))return;openTrip(el.dataset.trip);});}

function renderFavorites(){if(!state.db)return;const rows=[...state.favorites].map(id=>state.infos.get(id)).filter(Boolean);$('favoritesGrid').innerHTML=rows.map(tripCard).join('')||`<div class="empty-state" style="grid-column:1/-1"><span class="large-icon">☆</span><h2>お気に入りはまだありません</h2><p>列車カードの☆を押すと、ここに保存されます。</p><button class="primary-btn" data-view="trains">列車を探す</button></div>`;bindTripCards($('favoritesGrid'));bindViewButtons($('favoritesView'));}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);savePrefs();$('favoriteCount').textContent=state.favorites.size;if(state.selected?.trip[0]===id)$('favoriteButton').textContent=state.favorites.has(id)?'★':'☆';state.view==='favorites'?renderFavorites():renderTrips();toast(state.favorites.has(id)?'お気に入りに追加しました':'お気に入りから外しました');}
function toggleCompare(id){if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size>=3)return toast('比較できるのは3件までです');else state.compare.add(id);$('compareCount').textContent=state.compare.size;renderTrips();}
function renderCompare(){const rows=[...state.compare].map(id=>state.infos.get(id)).filter(Boolean);$('compareContent').innerHTML=rows.length?rows.map(i=>`<div class="compare-col"><span class="tag">${esc(i.route)}</span><h3>${esc(trainNumber(i.trip[0]))}</h3><dl><dt>輸送区間</dt><dd>${esc(i.from)} → ${esc(i.to)}</dd><dt>計画時刻</dt><dd>${displayTime(departureTime(i))} — ${displayTime(arrivalTime(i))}</dd><dt>所要時間</dt><dd>${durationText(i.duration)}</dd><dt>停車地点</dt><dd>${i.timeline.length}地点</dd><dt>輸送形態</dt><dd>${i.offrail?'鉄道＋オフレール':'鉄道'}</dd></dl><button type="button" class="text-btn" data-remove-compare="${esc(i.trip[0])}">比較から外す</button></div>`).join(''):`<div class="empty-state" style="grid-column:1/-1"><h2>比較する列車がありません</h2><p>列車一覧から最大3件選択できます。</p></div>`;$('compareContent').querySelectorAll('[data-remove-compare]').forEach(b=>b.onclick=()=>{toggleCompare(b.dataset.removeCompare);renderCompare();});}

function renderStations(){if(!state.db)return;const q=$('stationSearch').value.trim().toLowerCase();const rows=state.stations.filter(s=>`${s.name} ${s.code}`.toLowerCase().includes(q));$('stationList').innerHTML=rows.map(s=>`<div class="station-item ${state.selectedStation?.code===s.code?'active':''}" data-station="${s.code}"><b>${esc(s.name)}</b><span>${s.code}</span></div>`).join('');$('stationList').querySelectorAll('[data-station]').forEach(el=>el.onclick=()=>selectStation(el.dataset.station));}
function stationEvents(station){
  const seen=new Set(),events=[];for(const info of state.stationTrips.get(station.code)||[]){if(seen.has(info.trip[0]))continue;seen.add(info.trip[0]);const stop=info.timeline.find(s=>s.code===station.code);if(stop?.dep)events.push({info,time:stop.dep,type:'出発',other:info.to});if(stop?.arr&&stop.arr!==stop.dep)events.push({info,time:stop.arr,type:'到着',other:info.from});}
  return events.sort((a,b)=>nextDelta(a.time)-nextDelta(b.time));
}
function selectStation(code){state.selectedStation=state.stations.find(s=>s.code===code);renderStations();renderStationDetail();}
function renderStationDetail(){const s=state.selectedStation;if(!s)return;$('stationEmpty').classList.add('hidden');$('stationDetail').classList.remove('hidden');$('stationType').textContent=s.type;$('stationName').textContent=s.name;$('stationCode').textContent=`駅コード ${s.code}｜${s.lat.toFixed(5)}, ${s.lon.toFixed(5)}`;const events=stationEvents(s),infos=[...new Map(events.map(e=>[e.info.trip[0],e.info])).values()];$('stationTrips').textContent=`${infos.length.toLocaleString()}件`;$('stationNext').textContent=events[0]?`${displayTime(events[0].time)}（${nextDelta(events[0].time)}分後）`:'—';$('stationRoutes').textContent=`${new Set(infos.map(i=>i.route)).size}方面`;
  const filtered=events.filter(e=>state.boardMode==='all'||(state.boardMode==='departure'&&e.type==='出発')||(state.boardMode==='arrival'&&e.type==='到着')).slice(0,200);$('stationBoardBody').innerHTML=filtered.map(e=>`<tr data-trip="${esc(e.info.trip[0])}"><td><b>${displayTime(e.time)}</b></td><td><span class="tag">${e.type}</span></td><td class="train-name">${esc(trainNumber(e.info.trip[0]))}</td><td>${esc(e.other)}</td><td class="route-text">${esc(e.info.route)}</td><td>›</td></tr>`).join('')||'<tr><td colspan="6" class="empty-row">該当する計画はありません</td></tr>';bindTripOpen($('stationBoardBody'));}

function initMap(){
  if(state.map)return;state.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([36.3,138.2],5);state.mapLayers=[L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO'}),L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png',{attribution:'国土地理院'})];state.mapLayers[0].addTo(state.map);state.map.on('zoomend',updateStationMarkerScale);drawNetwork();
}
function stabilizeMap(after){if(!state.map)return;requestAnimationFrame(()=>setTimeout(()=>{state.map.invalidateSize({pan:false});updateStationMarkerScale();if(after)after();},90));}
function stationMarkerRadius(zoom,selected=false){return Math.min(14,Math.max(3,3+(zoom-5)*1.15))+(selected?2.5:0);}
function updateStationMarkerScale(){if(!state.networkLayer||!state.map)return;const zoom=state.map.getZoom();state.networkLayer.eachLayer(marker=>marker.setRadius(stationMarkerRadius(zoom,marker.options.stationCode===state.selectedStation?.code)).setStyle({weight:zoom>=9?2:1.5,fillOpacity:zoom>=8?.96:.82}));}
function focusStationOnMap(station,zoom=10){if(!station||!state.map)return;state.selectedStation=station;renderMapPanel();stabilizeMap(()=>{const lat=Number(station.lat),lon=Number(station.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)){logEvent('error','貨物地点の座標が不正です',`${station.name}: ${station.lat}, ${station.lon}`);return;}state.map.setView(L.latLng(lat,lon),zoom,{animate:false});updateStationMarkerScale();$('mapHint').innerHTML=`<b>${esc(station.name)}</b><span>${esc(station.type)}｜駅コード ${station.code}｜緯度 ${lat.toFixed(5)}・経度 ${lon.toFixed(5)}</span>`;logEvent('info','貨物地点を地図表示しました',`${station.name} [${lat.toFixed(5)}, ${lon.toFixed(5)}]`);});}
function drawNetwork(){if(!state.map)return;if(state.networkLayer)state.networkLayer.remove();state.networkLayer=L.layerGroup(state.stations.map(s=>L.circleMarker([s.lat,s.lon],{radius:stationMarkerRadius(state.map.getZoom()),color:'#167a5a',weight:1.5,fillColor:'#fff',fillOpacity:.82,stationCode:s.code}).bindTooltip(`${s.name}（${s.code}）`).on('click',()=>{$('mapSearch').value=s.name;focusStationOnMap(s,Math.max(8,state.map.getZoom()));}))).addTo(state.map);updateStationMarkerScale();}
function renderMapPanel(){if(!state.db)return;const q=$('mapSearch').value.trim().toLowerCase(),route=$('mapRoute').value;let rows=state.mapMode==='active'?uniqueInfos().filter(isActive):state.stations;
  if(state.mapMode==='active'){rows=rows.filter(i=>(!route||i.trip[1]===route)&&(!q||`${trainNumber(i.trip[0])} ${i.from} ${i.to}`.toLowerCase().includes(q)));$('mapList').innerHTML=rows.slice(0,200).map(i=>`<div class="map-list-item ${state.selected?.trip[0]===i.trip[0]?'active':''}" data-trip="${esc(i.trip[0])}"><b>${esc(trainNumber(i.trip[0]))}</b><span>${esc(i.from)} → ${esc(i.to)}｜進捗 ${tripProgress(i)}%</span></div>`).join('');$('mapList').querySelectorAll('[data-trip]').forEach(el=>el.onclick=()=>{const info=state.infos.get(el.dataset.trip);state.selected=info;renderMapPanel();showOnMainMap(info);});}
  else{rows=rows.filter(s=>!q||`${s.name} ${s.code}`.toLowerCase().includes(q));$('mapList').innerHTML=rows.map(s=>`<div class="map-list-item ${state.selectedStation?.code===s.code?'active':''}" data-map-station="${s.code}"><b>${esc(s.name)}</b><span>${s.type}｜駅コード ${s.code}｜関連 ${(state.stationTrips.get(s.code)||[]).length.toLocaleString()}件</span></div>`).join('');$('mapList').querySelectorAll('[data-map-station]').forEach(el=>el.onclick=()=>focusStationOnMap(state.stations.find(x=>x.code===el.dataset.mapStation),10));}}
async function getShape(info){const trip=info.trip;if(!state.shards.has(trip[4]))state.shards.set(trip[4],fetch(`./data/shapes/${trip[4]}.json`).then(r=>{if(!r.ok)throw Error('地図形状を取得できません');return r.json();}));return (await state.shards.get(trip[4]))[trip[3]]||[];}
function interpolate(points,ratio){if(!points.length)return null;const p=Math.max(0,Math.min(1,ratio))*(points.length-1),a=points[Math.floor(p)],b=points[Math.ceil(p)],f=p-Math.floor(p);return[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f];}
function routeSegments(points,timeline){if(points.length<2)return[];const indices=timeline.map(stop=>{let best=0,distance=Infinity;for(let i=0;i<points.length;i++){const d=(points[i][0]-stop.lat)**2+(points[i][1]-stop.lon)**2;if(d<distance){distance=d;best=i;}}return best;});const segments=[];for(let i=0;i<timeline.length-1;i++){let a=indices[i],b=indices[i+1];if(a>b)[a,b]=[b,a];const coords=points.slice(a,b+1);if(coords.length<2)continue;const road=!timeline[i].train||!timeline[i+1].train||/オフレール|営業所/.test(`${timeline[i].name} ${timeline[i+1].name}`);segments.push({coords,road});}return segments.length?segments:[{coords:points,road:false}];}
function routeFeature(points,info,weight=5){return L.featureGroup(routeSegments(points,info.timeline).map(segment=>L.polyline(segment.coords,{color:segment.road?'#e88b2f':'#167a5a',weight,opacity:.92,dashArray:segment.road?'8 7':null,lineCap:'round'})));}
async function showOnMainMap(info){initMap();try{const points=await getShape(info);if(state.routeLayer)state.routeLayer.remove();if(state.routeStops)state.routeStops.remove();if(state.trainMarker)state.trainMarker.remove();state.routeLayer=routeFeature(points,info,5).addTo(state.map);state.routeStops=L.layerGroup(info.timeline.map(s=>L.circleMarker([s.lat,s.lon],{radius:4,color:s.train?'#167a5a':'#e88b2f',weight:2,fillColor:'#fff',fillOpacity:1}).bindTooltip(`${s.name} ${displayTime(s.dep||s.arr)}｜${s.train?'鉄道':'オフレール接続'}`))).addTo(state.map);stabilizeMap(()=>state.map.fitBounds(state.routeLayer.getBounds(),{padding:[35,35],animate:false}));const rel=activeRelative(info),delay=delayRecord(info);if(rel!=null&&state.settings.estimate&&points.length){const pos=interpolate(points,(rel-info.first)/(info.duration||1));state.trainMarker=L.circleMarker(pos,{radius:7,color:'#3478f6',weight:4,fillColor:'#fff',fillOpacity:1}).addTo(state.map).bindTooltip(delay?'遅延反映後の推定位置':'時刻表からの推定位置');}$('mapHint').innerHTML=`<b>${esc(trainNumber(info.trip[0]))}${delay?` <span class="delay-badge">${esc(delay.status)}</span>`:''}</b><span>${esc(info.from)} → ${esc(info.to)}｜緑＝鉄道・橙点線＝オフレール</span>`;}catch(e){toast(e.message);logEvent('error','全国マップの経路表示に失敗しました',e.message);}}

async function openTrip(id){const info=state.infos.get(id);if(!info)return;state.selected=info;$('detailDrawer').classList.add('open');$('detailDrawer').setAttribute('aria-hidden','false');$('drawerBackdrop').classList.remove('hidden');$('favoriteButton').textContent=state.favorites.has(id)?'★':'☆';const progress=tripProgress(info),rel=activeRelative(info),delay=delayRecord(info),late=delayMinutes(info);let current=-1;if(rel!=null)for(let i=0;i<info.timeline.length;i++){const t=mins(info.timeline[i].dep||info.timeline[i].arr);if(t!=null&&t<=rel)current=i;}
  $('drawerContent').innerHTML=`<section class="detail-hero"><span class="tag">${esc(info.route)}</span><h2>${esc(trainNumber(id))}</h2><p>${esc(info.from)} → ${esc(info.to)}</p>${delay?`<div class="trip-delay"><span class="delay-badge">公式 ${esc(delay.status)}</span><br><b>現在地：${esc(delay.location)}</b>｜遅れ反映後の到着見込 ${displayTime(adjustedTime(arrivalTime(info),late))}<br><small>同じ列車番号を含む輸送計画に反映しています。</small></div>`:''}</section><div class="detail-kpis"><div><span>所要時間</span><b>${durationText(info.duration+late)}</b></div><div><span>停車地点</span><b>${info.timeline.length}地点</b></div><div><span>計画状態</span><b style="color:${delay?'var(--red)':rel!=null?'var(--brand)':'var(--muted)'}">${delay?'遅延情報あり':rel!=null?'運行時間帯':'時間帯外'}</b></div></div><div class="detail-progress"><div><b>${delay?'遅延反映後':'計画上'}の推定進捗</b><span>${progress}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${progress}%"></div></div></div><div class="detail-map"><div id="detailMap"></div></div><div class="timeline"><h3>運行タイムライン</h3>${info.timeline.map((s,i)=>`<div class="stop ${i===current?'current':''}"><div class="stop-time">${displayTime(s.dep||s.arr)}</div><div class="stop-track"></div><div class="stop-info"><b>${esc(s.name)}</b><small>駅コード ${s.code}｜着 ${displayTime(s.arr)}　発 ${displayTime(s.dep)}${s.cargo?'｜荷役時刻を含む':''}</small></div></div>`).join('')}</div>`;
  if(state.detailMap){state.detailMap.remove();state.detailMap=null;}state.detailMap=L.map('detailMap',{zoomControl:false,attributionControl:false,interactive:false}).setView([36.3,138.2],5);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png').addTo(state.detailMap);
  try{const points=await getShape(info),line=routeFeature(points,info,4).addTo(state.detailMap);state.detailMap.fitBounds(line.getBounds(),{padding:[12,12]});if(rel!=null&&state.settings.estimate&&points.length){L.circleMarker(interpolate(points,(rel-info.first)/(info.duration||1)),{radius:6,color:'#3478f6',weight:3,fillColor:'#fff',fillOpacity:1}).addTo(state.detailMap);}}catch(e){toast(e.message);}
}
function closeDrawer(){$('detailDrawer').classList.remove('open');$('detailDrawer').setAttribute('aria-hidden','true');$('drawerBackdrop').classList.add('hidden');}

function globalSuggestions(){const q=$('globalSearch').value.trim().toLowerCase();if(!q){$('searchSuggestions').classList.add('hidden');return;}const trips=uniqueInfos().filter(i=>`${trainNumber(i.trip[0])} ${i.from} ${i.to}`.toLowerCase().includes(q)).slice(0,5),stations=state.stations.filter(s=>`${s.name} ${s.code}`.toLowerCase().includes(q)).slice(0,3);$('searchSuggestions').innerHTML=[...trips.map(i=>`<button class="suggestion" data-trip="${esc(i.trip[0])}"><span><b>${esc(trainNumber(i.trip[0]))}</b><small>　${esc(i.from)} → ${esc(i.to)}</small></span><span>列車</span></button>`),...stations.map(s=>`<button class="suggestion" data-global-station="${s.code}"><span><b>${esc(s.name)}</b><small>　${s.code}</small></span><span>駅</span></button>`)].join('')||'<div class="empty-row">該当なし</div>';$('searchSuggestions').classList.remove('hidden');bindTripOpen($('searchSuggestions'));$('searchSuggestions').querySelectorAll('[data-global-station]').forEach(b=>b.onclick=()=>{setView('stations');selectStation(b.dataset.globalStation);$('searchSuggestions').classList.add('hidden');});}
function checkDate(){if(!state.db)return;const val=$('dateInput').value,start=parseDate(state.db.meta.start),end=parseDate(state.db.meta.end),invalid=val<start||val>end;$('dateNotice').classList.toggle('hidden',!invalid);$('dateNotice').textContent=`このGTFSの対象期間は ${start}〜${end} です。選択日は対象期間外です。`;renderDashboard();}
function refreshStatus(){clock();fetchFreightStatus({quiet:true});if(state.db){renderDashboard();if(state.view==='trains')renderTrips();if(state.view==='stations'&&state.selectedStation)renderStationDetail();toast('計画・遅延状況を更新しました');}}
function bindViewButtons(root=document){root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));}

function bindEvents(){
  bindViewButtons();$('guideButton').onclick=()=>$('guideDialog').showModal();$('bannerGuide').onclick=()=>$('guideDialog').showModal();$('settingsButton').onclick=$('topSettingsButton').onclick=()=>{$('tokenInput').value=ODPT_ACCESS_TOKEN;$('settingsDialog').showModal();};$('themeButton').onclick=()=>{state.settings.theme=actualTheme()==='dark'?'light':'dark';savePrefs();};$('refreshButton').onclick=refreshStatus;
  $('statusRefreshButton').onclick=()=>fetchFreightStatus();$('showDelaysButton').onclick=()=>{renderDelayDialog();$('delayDialog').showModal();};
  $('openMapButton').onclick=()=>setView('map');$('activeMapButton').onclick=()=>{state.mapMode='active';setView('map');document.querySelectorAll('[data-map-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mapMode==='active'));};$('dateInput').onchange=checkDate;
  $('globalSearch').oninput=globalSuggestions;$('globalSearch').onkeydown=e=>{if(e.key==='Enter'){setView('trains');$('trainSearch').value=e.target.value;$('searchSuggestions').classList.add('hidden');renderTrips();}};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('globalSearch').focus();}});
  ['trainSearch','routeSelect','statusSelect','sortSelect'].forEach(id=>$(id).addEventListener(id==='trainSearch'?'input':'change',()=>{state.visibleTrips=60;renderTrips();}));$('clearFilters').onclick=()=>{$('trainSearch').value='';$('routeSelect').value='';$('statusSelect').value='';$('sortSelect').value='departure';renderTrips();};$('loadMoreButton').onclick=()=>{state.visibleTrips+=60;renderTrips();};$('compareOpenButton').onclick=()=>{renderCompare();$('compareDialog').showModal();};
  $('stationSearch').oninput=renderStations;document.querySelectorAll('[data-board]').forEach(b=>b.onclick=()=>{state.boardMode=b.dataset.board;document.querySelectorAll('[data-board]').forEach(x=>x.classList.toggle('active',x===b));renderStationDetail();});$('stationMapButton').onclick=()=>{if(!state.selectedStation)return;const station=state.selectedStation;setView('map');focusStationOnMap(station,10);};
  $('closeDrawer').onclick=$('drawerBackdrop').onclick=closeDrawer;$('favoriteButton').onclick=()=>state.selected&&toggleFavorite(state.selected.trip[0]);$('printButton').onclick=()=>window.print();
  document.querySelectorAll('[data-map-mode]').forEach(b=>b.onclick=()=>{state.mapMode=b.dataset.mapMode;document.querySelectorAll('[data-map-mode]').forEach(x=>x.classList.toggle('active',x===b));renderMapPanel();});$('mapSearch').oninput=renderMapPanel;$('mapRoute').onchange=renderMapPanel;$('fitJapanButton').onclick=()=>stabilizeMap(()=>state.map.fitBounds([[30.5,129],[45.8,146]],{padding:[24,24],animate:false}));$('fitRouteButton').onclick=()=>state.routeLayer&&stabilizeMap(()=>state.map.fitBounds(state.routeLayer.getBounds(),{padding:[35,35],animate:false}));$('mapLayerButton').onclick=()=>{state.map.removeLayer(state.mapLayers[state.mapBase]);state.mapBase=(state.mapBase+1)%state.mapLayers.length;state.mapLayers[state.mapBase].addTo(state.map);};
  document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>{state.settings.theme=b.dataset.themeChoice;savePrefs();});$('densitySelect').onchange=e=>{state.settings.density=e.target.value;savePrefs();};$('delayToggle').onchange=e=>{state.settings.delay=e.target.checked;savePrefs();if(state.db){renderDashboard();renderTrips();}logEvent('info',e.target.checked?'遅延情報の反映を有効にしました':'遅延情報の反映を無効にしました');};$('estimateToggle').onchange=e=>{state.settings.estimate=e.target.checked;savePrefs();};$('autoRefreshToggle').onchange=e=>{state.settings.autoRefresh=e.target.checked;savePrefs();};$('showTokenButton').onclick=()=>{const show=$('tokenInput').type==='password';$('tokenInput').type=show?'text':'password';$('showTokenButton').textContent=show?'隠す':'表示';};$('connectionButton').onclick=()=>{window.open(ODPT_GTFS_URL,'_blank','noopener');toast('ODPTのGTFS接続先を開きました');};
  $('consoleButton').onclick=()=>{$('settingsDialog').close();renderConsole();$('consoleDialog').showModal();};$('consoleRefreshButton').onclick=()=>fetchFreightStatus();$('clearConsoleButton').onclick=()=>{state.logs=[];renderConsole();};$('copyConsoleButton').onclick=async()=>{const text=state.logs.map(x=>`${x.time.toISOString()} [${x.level.toUpperCase()}] ${x.message}${x.detail?` | ${x.detail}`:''}`).join('\n');await navigator.clipboard.writeText(text);toast('コンソールログをコピーしました');};
}

async function init(){
  loadPrefs();bindEvents();clock();setInterval(clock,1000);$('dateInput').value=localDate();$('tokenInput').value=ODPT_ACCESS_TOKEN;logEvent('info','Cargo Scopeを起動しました',`ブラウザ ${navigator.userAgent}`);fetchFreightStatus();
  try{logEvent('info','ローカルGTFSを読み込んでいます','./data/core.json');const response=await fetch('./data/core.json');if(!response.ok)throw Error('GTFS変換データが見つかりません');state.db=await response.json();for(const trip of state.db.trips)tripInfo(trip);buildIndexes();const options=Object.entries(state.db.routes).map(([id,r])=>`<option value="${id}">${esc(r.name)}</option>`).join('');$('routeSelect').insertAdjacentHTML('beforeend',options);$('mapRoute').insertAdjacentHTML('beforeend',options);$('navTripCount').textContent=state.db.trips.length.toLocaleString();$('favoriteCount').textContent=state.favorites.size;$('dataVersion').textContent=`GTFS ${state.db.meta.version}｜${parseDate(state.db.meta.start)}〜${parseDate(state.db.meta.end)}`;$('mapHint').innerHTML=`<b>全国${state.stations.length.toLocaleString()}地点</b><span>貨物地点をクリックすると関連する輸送計画を確認できます</span>`;$('dateInput').min=parseDate(state.db.meta.start);$('dateInput').max=parseDate(state.db.meta.end);checkDate();renderStations();logEvent('success','ローカルGTFSを読み込みました',`${state.db.trips.length.toLocaleString()}計画・${state.stations.length}地点・版${state.db.meta.version}`);}
  catch(error){logEvent('error','GTFSの読込に失敗しました',error.message);$('dashboardView').innerHTML=`<div class="empty-state"><span class="large-icon">!</span><h2>データを読み込めませんでした</h2><p>${esc(error.message)}</p></div>`;toast('GTFSの読込に失敗しました');}
}
window.addEventListener('error',event=>logEvent('error','ブラウザ実行エラー',`${event.message} (${event.filename}:${event.lineno})`));
window.addEventListener('unhandledrejection',event=>logEvent('error','未処理の非同期エラー',event.reason?.message||String(event.reason)));
init();
