tunnel: 5215cd34-d632-4836-bad8-6cf7ae3c27e0
credentials-file: /etc/cloudflared/credentials.json
protocol: http2

ingress:
- hostname: incident-api.tayunet-traininfo.com
  path: ^/server-monitor(?:/.*)?$
  service: http://127.0.0.1:5110
- hostname: history.tayunet-traininfo.com
  service: http://127.0.0.1:8787
- hostname: photo-api.tayunet-traininfo.com
  service: http://127.0.0.1:8790
- hostname: incident-api.tayunet-traininfo.com
  service: http://127.0.0.1:8795
- service: http_status:404
