name: Build and Deploy Knowledge Base

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行
    paths:
      - 'JREgyoumu/**' # JREgyoumuフォルダ内の変更のみを対象

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # トークンを設定して、後でpushできるようにする
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Jinja2 Markdown PyYAML

      - name: Run build script
        run: python JREgyoumu/build.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add JREgyoumu/
          # 変更があった場合のみコミット
          if ! git diff --staged --quiet; then
            git commit -m "Update knowledge base site [ci skip]"
            git push
          else
            echo "No changes to commit."
          fi
