name: Update JR Freight Status

# このワークフローが実行されるタイミングを指定
on:
  workflow_dispatch: # 手動実行を許可
  schedule:
    # 1時間に1回実行 (cron形式)
    # 毎時0分に実行されます
    - cron: '*/15 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を許可

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 必要なPythonライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. 輸送状況を更新するスクリプトを実行
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動的に提供されるトークン
        run: python JRFtest/update.py
